package Wires;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import static java.lang.Thread.sleep;

/**
 * Created by zychp_w10 on 23.05.2017.
 */
public class Prototype {
    private JButton runButton;
    private JPanel drawpanel;
    private JPanel controlpanel;
    private JPanel mainpanel;
    private JButton electronTailButton;
    private JButton electronHeadButton;
    private JButton conductorButton;
    private JFormattedTextField generationsTextField1;
    private JButton stopButton;
    private JFormattedTextField delayTextField1;
    private JLabel gennumLabel;

    public Prototype() throws Exception {
        DrawBoard drawboard = new DrawBoard(5, 5, 5);
        WireLogic logic = new WireLogic(5, 5);
        EventQueue.invokeLater(() ->
        {
            JFrame frame = new JFrame();
            frame.pack();
            frame.setTitle("Wirewold");
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.setLocationByPlatform(true);
            frame.setVisible(true);
        });

        for (int i = 0; i < 100; i++) {
            logic.tick();
            drawboard.setActual(logic.getEng().getBefore());
            drawboard.repaint();
            sleep(200);
        }
        System.out.println("END");


        runButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

            }
        });
        stopButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

            }
        });
    }

    public static void main(String[] args) throws Exception {
        Prototype prt = new Prototype();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainpanel = new JPanel();
        mainpanel.setLayout(new GridBagLayout());
        controlpanel = new JPanel();
        controlpanel.setLayout(new GridBagLayout());
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        mainpanel.add(controlpanel, gbc);
        runButton = new JButton();
        runButton.setText("Run");
        runButton.setVerticalAlignment(3);
        runButton.setVerticalTextPosition(3);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 10;
        gbc.anchor = GridBagConstraints.SOUTH;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        controlpanel.add(runButton, gbc);
        electronTailButton = new JButton();
        electronTailButton.setBackground(new Color(-14601039));
        electronTailButton.setForeground(new Color(-1));
        electronTailButton.setText("Electron tail");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        controlpanel.add(electronTailButton, gbc);
        conductorButton = new JButton();
        conductorButton.setBackground(new Color(-924610));
        conductorButton.setEnabled(true);
        conductorButton.setForeground(new Color(-1));
        conductorButton.setHideActionText(false);
        conductorButton.setText("Conductor");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        controlpanel.add(conductorButton, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.weighty = 5.0;
        gbc.fill = GridBagConstraints.VERTICAL;
        controlpanel.add(spacer1, gbc);
        generationsTextField1 = new JFormattedTextField();
        generationsTextField1.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 9;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        controlpanel.add(generationsTextField1, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("Generations:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 8;
        gbc.anchor = GridBagConstraints.WEST;
        controlpanel.add(label1, gbc);
        electronHeadButton = new JButton();
        electronHeadButton.setBackground(new Color(-4521972));
        electronHeadButton.setForeground(new Color(-1));
        electronHeadButton.setText("Electron head");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        controlpanel.add(electronHeadButton, gbc);
        stopButton = new JButton();
        stopButton.setText("Stop");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 11;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        controlpanel.add(stopButton, gbc);
        delayTextField1 = new JFormattedTextField();
        delayTextField1.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        controlpanel.add(delayTextField1, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Delay:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        controlpanel.add(label2, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Generation no:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        controlpanel.add(label3, gbc);
        gennumLabel = new JLabel();
        gennumLabel.setHorizontalAlignment(0);
        gennumLabel.setHorizontalTextPosition(0);
        gennumLabel.setText("gennum");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        controlpanel.add(gennumLabel, gbc);
        drawpanel = new JPanel();
        drawpanel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 20.0;
        gbc.weighty = 20.0;
        gbc.fill = GridBagConstraints.BOTH;
        mainpanel.add(drawpanel, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainpanel;
    }
}